In [3]:
import numpy as np

In [18]:
#a 에는 리스트
a = [1, 2, 3, 4, 5]
x = np.array(a)
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#배열 곱셈
x = np.array([1, 2, 3, 4, 5])
x_2 = x * 2
print(x_2)

[ 2  4  6  8 10]


In [ ]:
#배열 차원 확인
x_1 = np.array([1, 2, 3])
x_2 = np.array([[1, 2, 3], [4, 5, 6]])
x_3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(x_1.ndim)
print(x_2.ndim)
print(x_3.ndim)



In [ ]:
#배열 모양 확인
x_1 = np.array([1, 2, 3])
x_2 = np.array([[1, 2, 3], [4, 5, 6]])
x_3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

for x in [x_1, x_2, x_3]:
    print('-----')
    print(x.ndim, x.shape)

In [10]:
# 임의 배열 생성
x = np.zeros(3)
print(x)
y= np.ones((3, 4))
print(y)
z = np.empty((2, 3))
print(x)
a = np.random.rand(2, 3)
print(a)
b = np.random.randint(1, 21, size = 20).reshape(4, 5)
print(b)

[0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0. 0. 0.]
[[0.19462849 0.81109871 0.45773454]
 [0.45693703 0.50249078 0.84220925]]
[[ 4 15  8 11 15]
 [ 7  3  2  7  1]
 [ 8 10 16 16 20]
 [ 1  3  2  7 16]]


In [25]:
# 배열 연산
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x + y)
print(x - y)
print(x * y)
print(x / y)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
#배열 내적
x = np.array([[1, 2, 3],
              [4, 5, 6]])
y = np.array([[11, 12],
              [13, 14],
              [15, 16]])
print(np.dot(x, y))

[[ 82  88]
 [199 214]]


In [ ]:
#배열 변환
x = np.array([[10, 11, 12],
              [13, 14, 15]])
print(x.reshape((3, -1)))
print(x.flatten())

In [ ]:
#배열 추출
x = np.array([[1, 2, 3],
              [4, 5, 6]])
print(x[:, 1])

y = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(y[1::2])

z = y[y % 2 == 0]
print(z)

In [ ]:
#배열 결합
x = np.array([[1, 2, 3],
              [4, 5, 6]])
y = np.array([[10, 11, 12],
              [13, 14, 15]])
print(np.concatenate([x, y], 0))
print(np.concatenate([x, y], 1))

In [ ]:
#배열 연산2
x = np.array([[1, 2, 3],
              [4, 5, 6]])
print(np.max(x))
print(np.min(x))
print(np.sum(x))
print(np.prod(x)) #요소끼리 전부 곱하기기
print(np.mean(x)) #평균
print(np.std(x)) #표준편차
print(np.var(x)) #분산
print(np.median(x)) #중앙값

In [ ]:
#배열 연산3
x = np.array([[1, 2, 3],
              [4, 5, 6]])
print(np.log(x))
print(np.sqrt(x))
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.pi) #원주율율

In [ ]:
x =np.arange(24).reshape(2,3,4)
print(x)

print(np.sum(x, axis = 1))
print(np.mean(x, axis=0))
print(np.max(x, axis=0)) 
print(np.min(x, axis=1))