In [ ]:
import numpy as np

# 1부터 9까지의 숫자를 가진 3x3 배열을 만들어 보세요.
x = list(range(1, 10))
y = np.array(x)
array = y.reshape(3, 3)
print(array)

# 이 배열을 사용해서 새로운 배열을 만들어 보세요.
# 조건: 짝수만 골라내고, 그 짝수들을 모두 제곱하세요.
a = array.reshape(-1, )
print(a)
b = a[1::2]
result = b**2
print(result)


#모범답안
"""import numpy as np

x = np.arange(1, 10).reshape(3, 3)
result = x[x % 2 == 0] ** 2
print(result)"""

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[ 4 16 36 64]


In [ ]:
import numpy as np

# 1부터 20까지의 정수를 무작위로 섞어 4x5 배열로 만드세요.
# (seed를 설정해서 재실행해도 같은 결과가 나오게 하세요)
# 조건1: 배열 전체에서 3의 배수이면서 5보다 큰 값만 고르세요.
# 조건2: 그 값들의 평균을 구하고, 평균보다 큰 값들만 제곱한 새로운 배열을 만드세요.
# 최종적으로 그 배열을 출력하세요.

# 예: 4x5 배열 -> 조건을 만족하는 값 -> 평균 -> 평균 초과 값 -> 제곱
np.random.seed(23)
array = np.random.randint(1, 21, size = 20).reshape(4, 5)
print(array)

a = array[array % 3 == 0]
x = a[a > 5]
print(x)

b = np.mean(x)
c = x[x > b]
y = c**2
print(y)


#모범답안
"""import numpy as np

np.random.seed(23)
arr = np.random.randint(1, 21, size=20).reshape(4, 5)

# 3의 배수이면서 5보다 큰 값 중에서
# 평균보다 큰 값만 제곱
result = arr[(arr % 3 == 0) & (arr > 5)]
result = result[result > result.mean()] ** 2

print(result)"""


[[20  7  9 10  9]
 [14 13  8 20  7]
 [14 13 18  3 12]
 [ 6  1 13 17 10]]
[ 9  9 18 12  6]
[324 144]
